#!/bin/bash
cd `dirname $0`
if [ $# == 0 ] ; then
    echo "USAGE: ./run_edge port1 port2"
    echo "run fail"
    exit 1;
fi
source ../venv/bin/activate
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
for i in $@; do
    port=$i
    export PORT=$port
    pid=`sudo netstat -lnp  | grep $port  | grep -v tcp6 | awk '{print $7}'| awk -F/ '{print $1}'`
    if [ "$pid" != "" ] ; then
      echo "start fail : port $port already occupied"
      echo "kill "+`sudo netstat -lnp  | grep $port  | grep -v tcp6 | awk '{print $7}'`
      kill $pid
      # exit
    fi
    nohup python edge_server/edge_main.py > edge_$port.log 2>&1 &
    sleep 1
    for x in `seq 0 5`
    do
      pid=`sudo netstat -lnp  | grep $port  | grep -v tcp6 | awk '{print $7}' | awk -F/ '{print $1}'`
      if [ "$pid" != "" ] ; then
        break
      else
        sleep 1
      fi
    done
    if [ "$pid" != "" ] ; then
      echo "start succ ; pid:$pid"
    else
      echo "start failed"
      tail edge_$port.log
    fi
    deactivate
done
