#!/bin/bash
cd `dirname $0`
port=5555
source ../venv/bin/activate
export PORT=$port
pid=`sudo netstat -lnp  | grep $port  | grep -v tcp6 | awk '{print $7}'| awk -F/ '{print $1}'`
if [ "$pid" != "" ] ; then
  echo "start fail : port $port already occupied"
  echo "kill "+`sudo netstat -lnp  | grep $port  | grep -v tcp6 | awk '{print $7}'`
  kill $pid
  # exit
fi
nohup python center_main.py > center.log 2>&1 &
sleep 1
for x in `seq 0 5`
do
  pid=`sudo netstat -lnp  | grep $port  | grep -v tcp6 | awk '{print $7}' | awk -F/ '{print $1}'`
  if [ "$pid" != "" ] ; then
    break
  else
    sleep 1
  fi
done
if [ "$pid" != "" ] ; then
  echo "start succ ; pid:$pid"
else
  echo "start failed"
  tail center.log
fi
deactivate
